---
proxmox_host: 192.168.1.250
proxmox_user: root@pam
proxmox_password: "{{ vault_proxmox_password }}"
proxmox_node: pve
vm_memory: 4096
vm_cores: 2
vm_storage: local
vm_disk_size: 30G
vm_iso: ubuntu-22.04.iso
