---
- name: Initialize Terraform
  command: "terraform apply -auto-approve"
  args:
    chdir: "/root/ansibleproxmox/terraform"
  register: result1
  tags: t1

- name: Apply Terraform configuration
  command: "terraform apply -auto-approve"
  args:
    chdir: "/root/ansibleproxmox/terraform"
  register: result2
  tags: t2
  environment:
    TF_VAR_proxmox_password: "{{ vault_proxmox_password }}"
