---
- name: Provision and configure Proxmox VMs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run Terraform to provision VMs
      include_role:
        name: terraform

- name: Configure Proxmox VMs
  hosts: all
  gather_facts: false
  roles:
    - update_vm
