---
- name: Provision and configure Proxmox VMs
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vault.yml

  tasks:
    - name: Run Terraform to provision VMs
      include_role:
        name: terraform_provision
