---
- hosts: all
  become: yes
  vars:
    user_name: "{{ lookup('env', 'USER_NAME') }}"

  tasks:
    - name: Ensure '{{ user_name }}' user is present
      ansible.builtin.user:
        name: "{{ user_name }}"
        groups: "sudo"
        state: present
        shell: /bin/bash

    - name: Ensure '{{ user_name }}' user has sudo privileges without password
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ user_name }}"
        content: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
        mode: '0440'
