---
- name: Create VM from ISO
  proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ item.id }}"
    name: "{{ item.name }}"
    memory: "{{ vm_memory }}"
    cores: "{{ vm_cores }}"
    storage: "{{ vm_storage }}"
    iso: "{{ vm_iso }}"
    ide2: "{{ vm_storage }}:iso/{{ vm_iso }}"
    sata0: "{{ vm_storage }}:{{ vm_disk_size }}"
    net0: "virtio,bridge=vmbr0"
    ostype: l26
    state: present
  with_items: "{{ vm_list }}"
